version: '3.9'

include:
  - docker-compose.builders.yml  
  - docker-compose.development.yml  
  - docker-compose.test.yml  
  - docker-compose.tooling.yml  
  - docker-compose.production.yml

volumes:
  db_data:
  gem_cache:
  node_modules:
  redis:

